-- 코드를 입력하세요
SELECT O.REST_ID, O.REST_NAME, O.FOOD_TYPE, O.FAVORITES, O.ADDRESS, ROUND(AVG(W.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW W JOIN REST_INFO O ON W.REST_ID = O.REST_ID
WHERE O.ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC